name: CI/CD

on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build app
        run: yarn build-prod

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy app / Sync S3
        run: aws s3 sync ./out s3://frontend-static-nextjs
